# Generated by Django 3.1.5 on 2021-11-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20211120_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures', verbose_name='تصاویر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Blog.post'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='videos', verbose_name='ویدیو')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Blog.post')),
            ],
        ),
    ]
