# Generated by Django 3.1.5 on 2021-12-13 12:14

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20211213_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
    ]
